dist: xenial   # required for Python >= 3.7
language: python            # this works for Linux but is an error on macOS or Windows
cache: pip
  script:
    - pytest
directories:
- $HOME/.cache/pip
matrix:
  include:
    allow_failures:
    
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
script: pytest

after_success:
  # Upload coverage data to codecov
  - codecov
notifications:
template:
- "%{repository_name}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
  email: false

