language: python            # this works for Linux but is an error on macOS or Windows
directories:
- $HOME/.cache/pip
matrix:
  include:
    allow_failures:
    - python: pypy3
    
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
- pip install --upgrade pip  # all three OSes agree about 'pip3'in version 3.6 < 3.0
- pip install -r requirements.txt
  # Self
- pip install -e .


script:
  # Fast syntax check failures for more rapid feedback to submitters
  # (Travis-oriented metatask that version checks Python, installs, runs.)
  - inv travis.blacken
  # I have this in my git pre-push hook, but contributors probably don't
  - flake8
  # Execute full test suite + coverage, as the new sudo-capable user
  - inv travis.sudo-coverage
  # Execute integration tests too. TODO: merge under coverage...somehow
  # NOTE: this also runs as the sudo-capable user, even if it's not necessarily
  # doing any sudo'ing itself - the sudo-capable user is also the ssh-able
  # user...
  - inv travis.sudo-run "inv integration --capture=no"
  # Websites build OK? (Not on PyPy3, Sphinx is all "who the hell are you?" =/
  - "if [[ $TRAVIS_PYTHON_VERSION != 'pypy3' ]]; then inv sites www.doctest docs.doctest; fi"
  # Did we break setup.py?
  - inv travis.test-installation --package=commi3 --sanity="fab --version"
  # Test distribution builds.
  - inv travis.test-packaging --package=commi3 --sanity="fab --version"
  # Again, but as 'commi3'
  - rm -rf tmp
  - pip uninstall -y commi3
  - "PACKAGE_AS_FABRIC2=yes inv travis.test-packaging --package=commi3 --sanity=\"commi3 --version\""
  - inv sanity-test-from-v1
after_success:
  # Upload coverage data to codecov
  - codecov
notifications:
  irc:

    template:
      - "%{repository_name}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
  email: false

